#!/bin/sh

set -e

DOTFILES="${HOME}/.dotfiles"

# Ask for local dotfiles repo
if [ ! -d "${DOTFILES}/local" ];
then
  echo "Personal Dotfiles Github Username (leave empty to skip)?"
  read -r github_user
fi

echo "--> Authorising Administrator Access"
sudo -v

while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "--> Configuring Initial Settings"
/bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/itsmycargo/dotfiles/master/setup)"

# Check for login shell
if [ "$SHELL" != "/bin/zsh" ];
then
  echo "--> Shell: /bin/zsh"
  chsh -s /bin/zsh
fi

# Install homebrew
if [ -z "$(command -v brew)" ];
then
  echo "--> Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ -z "$(command -v rcup)" ];
then
  echo "--> Installing rcm"
  /usr/local/bin/brew tap thoughtbot/formulae
  /usr/local/bin/brew install rcm
fi

if [ ! -d "${DOTFILES}/itsmycargo" ];
then
  echo "--> Clone Dotfiles Repository"
  git clone https://github.com/itsmycargo/dotfiles.git "${DOTFILES}/itsmycargo"
else
  (cd "${DOTFILES}/itsmycargo" ; git pull )
fi

if [ -n "${github_user}" ] && [ ! -d "${DOTFILES}/local" ];
then
  git clone "https://github.com/${github_user}/dotfiles.git" "${DOTFILES}/local"
else
  (cd "${DOTFILES}/local" ; git pull )
fi

echo "--> Install Dotfiles"
env RCRC="${DOTFILES}/itsmycargo/rcrc" rcup

# Run additional install scripts
for script in "${DOTFILES}"/itsmycargo/install.d/*.sh "${DOTFILES}"/local/install.d/*.sh;
do
  sh "${script}"
done

# Install Brews
for brewfile in "${DOTFILES}"/itsmycargo/install.d/*.sh "${DOTFILES}"/local/install.d/*.sh;
do
  $(command -v brew) bundle install --file="${brewfile}"
done
