#!/bin/bash

set -e

if [ -n "${DOTFILES_DEBUG}" ];
then
  set -x
fi

DOTFILES_ROOT="${HOME}/.dotfiles"
mkdir -p "${DOTFILES_ROOT}"
export DOTFILES_ROOT

# Ask for private dotfiles repo
if [ ! -d "${DOTFILES_ROOT}/private" ];
then
  echo "Personal Dotfiles Github Username (leave empty to skip)?"
  read -r github_user
fi

echo "--> Authorising Administrator Access"
sudo -v

while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install homebrew
if [ -z "$(command -v brew)" ];
then
  echo "--> Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ -z "$(command -v rcup)" ];
then
  echo "--> Installing rcm"
  /usr/local/bin/brew tap thoughtbot/formulae
  /usr/local/bin/brew install rcm
fi

if [ ! -d "${DOTFILES_ROOT}/itsmycargo" ];
then
  echo "--> Clone Dotfiles Repository"
  git clone https://github.com/itsmycargo/dotfiles.git "${DOTFILES_ROOT}/itsmycargo"
else
  (cd "${DOTFILES_ROOT}/itsmycargo" ; git pull --rebase --autostash --quiet )
fi

if [ -n "${github_user}" ];
then
  if [ ! -d "${DOTFILES_ROOT}/private" ];
  then
    git clone "https://github.com/${github_user}/dotfiles.git" "${DOTFILES_ROOT}/private"
  else
    (cd "${DOTFILES_ROOT}/private" ; git pull --rebase --autostash --quiet )
  fi
fi

# Run additional install scripts
echo "--> Install Scripts"
shopt -s nullglob
for script in "${DOTFILES_ROOT}"/itsmycargo/install.d/*.sh "${DOTFILES_ROOT}"/private/install.d/*.sh;
do
  sh "${script}"
done
shopt -u nullglob

echo "--> Install Dotfiles"
env RCRC="${DOTFILES_ROOT}/itsmycargo/rcrc" rcup

# Run additional post-install scripts
echo "--> Post-Install Scripts"
shopt -s nullglob
for script in "${DOTFILES_ROOT}"/itsmycargo/post-install.d/*.sh "${DOTFILES_ROOT}"/private/post-install.d/*.sh;
do
  sh "${script}"
done
shopt -u nullglob
