#!/bin/sh

set -e

DOTFILES="${HOME}/.dotfiles"
mkdir -p "${DOTFILES}"

# Ask for local dotfiles repo
if [ ! -d "${DOTFILES}/local" ];
then
  echo "Personal Dotfiles Github Username (leave empty to skip)?"
  read -r github_user
fi

echo "--> Authorising Administrator Access"
sudo -v

while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "--> Configuring Initial Settings"
/bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/itsmycargo/dotfiles/master/setup)"

# Check for login shell
if [ "$SHELL" != "/bin/zsh" ];
then
  echo "--> Shell: /bin/zsh"
  chsh -s /bin/zsh
fi

# Install homebrew
if [ -z "$(command -v brew)" ];
then
  echo "--> Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ -z "$(command -v rcup)" ];
then
  echo "--> Installing rcm"
  /usr/local/bin/brew tap thoughtbot/formulae
  /usr/local/bin/brew install rcm
fi

if [ ! -d "${DOTFILES}/itsmycargo" ];
then
  echo "--> Clone Dotfiles Repository"
  git clone https://github.com/itsmycargo/dotfiles.git "${DOTFILES}/itsmycargo"
else
  (cd "${DOTFILES}/itsmycargo" ; git pull )
fi

if [ -n "${github_user}" ];
then
  if [ ! -d "${DOTFILES}/local" ];
  then
    git clone "https://github.com/${github_user}/dotfiles.git" "${DOTFILES}/local"
  else
    (cd "${DOTFILES}/local" ; git pull )
  fi
fi

echo "--> Install Dotfiles"
env RCRC="${DOTFILES}/itsmycargo/rcrc" rcup

# Run additional install scripts
echo "--> Install Scripts"
shopt -s nullglob
for script in "${DOTFILES}"/itsmycargo/install.d/*.sh "${DOTFILES}"/local/install.d/*.sh;
do
  sh "${script}"
done
shopt -u nullglob

# Install Brews
echo "--> Installing Brews"
shopt -s nullglob
for brewfile in "${DOTFILES}"/{itsmycargo,local}/Brewfile;
do
  [ -e "${brewfile}" ] && $(command -v brew) bundle install --file="${brewfile}"
done
shopt -u nullglob

# Run additional post-install scripts
echo "--> Post-Install Scripts"
shopt -s nullglob
for script in "${DOTFILES}"/itsmycargo/post-install.d/*.sh "${DOTFILES}"/local/post-install.d/*.sh;
do
  sh "${script}"
done
shopt -u nullglob
