#!/bin/sh

set -e

if [ -n "${DOTFILES_DEBUG}" ];
then
  set -x
fi

# Set up correct computer name
COMPUTER_NAME="$(id -un)-itsmycargo"
if [ "$(scutil --get ComputerName)" != "${COMPUTER_NAME}" ];
then
  sudo scutil --set ComputerName "${COMPUTER_NAME}"
  sudo scutil --set LocalHostName "${COMPUTER_NAME}"
  sudo scutil --set HostName "${COMPUTER_NAME}"
fi
